CREATE TABLE "finnhub_fundamentals" (
	"ticker" text PRIMARY KEY NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finnhub_pe_ratio" numeric,
	"finnhub_pb_ratio" numeric,
	"finnhub_ps_ratio" numeric,
	"finnhub_price_to_book" numeric,
	"finnhub_ev" numeric,
	"finnhub_market_cap" numeric,
	"finnhub_gross_margin" numeric,
	"finnhub_operating_margin" numeric,
	"finnhub_net_margin" numeric,
	"finnhub_fcf_margin" numeric,
	"finnhub_return_on_equity" numeric,
	"finnhub_return_on_assets" numeric,
	"finnhub_roic" numeric,
	"finnhub_revenue_growth" numeric,
	"finnhub_eps_growth" numeric,
	"finnhub_debt_to_equity" numeric,
	"finnhub_long_term_debt_to_equity" numeric,
	"finnhub_net_debt_to_equity" numeric,
	"finnhub_current_ratio" numeric,
	"finnhub_quick_ratio" numeric,
	"finnhub_fcf_per_share" numeric,
	"finnhub_book_value" numeric,
	"finnhub_beta" numeric,
	"finnhub_eps" numeric,
	"finnhub_ebit_per_share" numeric,
	"finnhub_earnings_per_share" numeric,
	"finnhub_52week_high" numeric,
	"finnhub_52week_low" numeric
);
