import { Router, type IRouter } from "express";
import healthRouter from "./health";
import stocksRouter from "./stocks";
import indicatorsRouter from "./indicators";
import optionsRouter from "./options";
import technicalRouter from "./technical";
import dailyBriefRouter from "./daily-brief";
import macroRouter from "./macro";
import fundamentalsRouter from "./fundamentals";
import technicalsRouter from "./technicals";
import explainRouter from "./explain";
import sdmRouter from "./sdm";
import macroRegimeRouter from "./macro-regime";
import authRouter from "./auth";
import watchlistRouter from "./watchlist";
import scoringConfigRouter from "./scoring-config";
import feedRouter from "./feed";
import adminCacheRouter from "./admin-cache";
import portfolioIngestRouter from "./portfolio-ingest";
import portfolioSnapshotRouter from "./portfolio-snapshot";
import cotRouter from "./macro-cot";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(watchlistRouter);
router.use(scoringConfigRouter);
router.use(feedRouter);
router.use(stocksRouter);
router.use(indicatorsRouter);
router.use(optionsRouter);
router.use(technicalRouter);
router.use(dailyBriefRouter);
router.use("/macro", macroRouter);
router.use(fundamentalsRouter);
router.use(technicalsRouter);
router.use(explainRouter);
router.use(sdmRouter);
router.use(macroRegimeRouter);
router.use(adminCacheRouter);
router.use(portfolioIngestRouter);
router.use(portfolioSnapshotRouter);
router.use(cotRouter);

export default router;
